### ISSUE TITLE
Related projects

### ISSUE THREAD

**Issue by ypid** [anthill/Python_OpeningHours#3]
Hi

I just stumbled across this project and you might be interested in this [little overview and further development of OSM opening_hours implementations](https://github.com/opening-hours/opening_hours.js/issues/136). Would be interesting to hear your story on this.

**Comment by Asphahyre** [comment]
Hi

I needed to manipulate the OSM opening hours standard since it's the only one I found doing its job.
I rewrote it entirely [in C first](https://github.com/anthill/C_OpeningHours), as I needed instantiation and deletion as fast as possible.
Moreover, as C is a low-level language, this implementation can be easily wrapped into other languages; that's what I did with this repository, to use it in some other projects.

It's far from a complete library yet, but I think the `is_open()` method was the real base to be able to call that an _implementation_.

**Comment by ypid** [comment]
Thanks for your feedback. An C implementation is definitely interesting for the mentioned reason to allow easy bindings. Did you see the [opening_hours_grammar](https://github.com/opening-hours/opening_hours_grammar)? I think when you write a parser yourself, it can get pretty complicated :wink:
But I think C takes a bit more development time compared to something like JavaScript or Python?

Also, what do you think about the [rewrite in Haxe](https://github.com/opening-hours/opening_hours.js/issues/136) (Haxe is able to generate native C++ code)?

**Comment by Asphahyre** [comment]
I tried to understand the format through the [OSM documentation here](https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification).

Yeah, that was pretty complicated to understand, and I found some of syntactically correct strings unsupported [around here](http://openingh.openstreetmap.de/evaluation_tool/?setLng=fr); I ignored a lot of "tricky" cases to focus to the most important.
Indeed, it took me a week to achieve this first version, but the wasted time during the development is the time saved for the run-time, I thought. :smile:

I didn't know such a language existed, and I think it's a good idea since the main problem of this standard is its portability (with the amount of features in each language) more than the speed I focused.
However, I am really interested in the performances of your generated code.

**Comment by ypid** [comment]
> it took me a week to achieve this first version

Very impressive :wink: I am maintaining [opening_hours.js](https://github.com/opening-hours/opening_hours.js) for almost three years now and there is still so much stuff to do. It is the 80/20 thing I guess :smile:

The targets of Haxe can be optimized when needed. I checked the C++ code generated by https://github.com/ypid/suncalc and it does not look too bad. I am sure modern C++ compilers can already heavily optimize that to a degree where I think it becomes reasonable to just generate the code.

> I found some of syntactically correct strings unsupported around here; I ignored a lot of "tricky" cases to focus to the most important.

Anything which is not [already tracked](https://github.com/opening-hours/opening_hours.js/issues)? Because [opening_hours.js](https://github.com/opening-hours/opening_hours.js) is supposed to be the reference implementation :wink: I know there are a few [very rarely used cases](https://github.com/opening-hours/opening_hours.js/issues/25).

**Comment by Asphahyre** [comment]
Thank you. :smile:
I am not a huge fan of JavaScript, but I may be able to contribute a bit to the project. :smiley: 

Indeed, Haxe seems to have a pretty clear syntax, object-oriented; I do think conversion should be easy, and seen some code, I don't think it would overload as much the converted code, allowing compilers' optimizations to be a bit more efficient, I agree. :smile: 

I don't really remember, I had unexpected tokens. Moreover, it might be a mistake from me for some of them, I'll report them if I find them back when I'll have enough time to work on it again! :smiley:
